name: IntegrationTest
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}/${{ matrix.julia-version }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ["1"]
        package:
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceI}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceII}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceIII}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceIV}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceV}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Integrators_I}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Integrators_II}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Regression_I}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Regression_II}
          - {user: SciML, repo: SimpleDiffEq.jl, group: Core}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      julia-arch: "x64"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
